# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ssrnpaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField(unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('downloads', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ssrnpaper',
            },
        ),
    ]
